version: "3.7"

services:
  fluentd:
    build: ./fluentd
    volumes:
      - ./fluentd/conf:/fluentd/etc
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    networks: 
      - eagle-eye-net

networks:
  your-net:
    external: true
